config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
root to: "top#index"
resources :pictures

devise_for :users, controllers: {
   registrations: "users/registrations",
   omniauth_callbacks: "users/omniauth_callbacks"
}

 if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
 end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :title, presence: true
  mount_uploader :image, ImageUploader

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  has_many :pictures

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    # user = User.find_by(email: auth.info.email)
    user = User.find_by(provider: auth.provider, uid: auth.uid)



    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
    
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
   end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
   user = User.find_by(provider: auth.provider, uid: auth.uid)

   unless user
     user = User.new(
         name:     auth.info.nickname,
         image_url: auth.info.image,
         provider: auth.provider,
         uid:      auth.uid,
         email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
         password: Devise.friendly_token[0, 20]
     )
     user.skip_confirmation!
     user.save
   end
   user
   end

   def self.create_unique_string
    SecureRandom.uuid
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protect_from_forgery with: :exception

 # before_actionで下で定義したメソッドを実行
 before_action :configure_permitted_parameters, if: :devise_controller?

 #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
 PERMISSIBLE_ATTRIBUTES = %i(name, email)

 protected

   #deviseのストロングパラメーターにカラム追加するメソッドを定義
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
     devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
   end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_blog, only: [:edit, :update, :destroy]



  def index
   @pictures = Picture.all
  end

  def new
   @picture = Picture.new
  end

  def create
   @picture =  Picture.new(pictures_params)
   @picture.user_id = current_user.id
    if @picture.save
     redirect_to root_path, notice: "写真をアップロードしました！"
     NoticeMailer.sendmail_picture(@picture).deliver
    else
     render 'new'
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
     if @picture.update(pictures_params)
       redirect_to root_path, notice:"更新しました！"
     else
       render'edit'
     end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to root_path
  end

  private
    def pictures_params
      params.require(:picture).permit(:title, :content, :image, :image_cache, :remove_image)
    end

    def set_blog
      @picture = Picture.find(params[:id])
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @pictures = Picture.all
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <%= f.error_messages! %>

  <%= f.label :タイトル %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content %>
  <br>
  <div class="field">
    <% if @picture.image? %>
      <div class="thumbnail">
      <%= image_tag @picture.image.url %>
    </div>
  <% end %><br>
    <%= f.label :画像 %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @picture.persisted? && @picture.image? %>
      <label>
      <%= f.check_box :remove_image %>
      画像を削除
    </label>
  <% end %>
  </div>
  <%= f.submit %>


<% end %>


<%= link_to "一覧TOP", root_path %>

app/views/pictures/edit.html.erb
<h3>編集画面</h3>

<%= render 'form' %>

app/views/pictures/index.html.erb
<p><%= notice %></p>

<h1>写真一覧</h1>

<% @pictures.each do |picture| %>
  <p>タイトル:<%= picture.title %></p>
  <p>本文:<%= picture.content %></p>
  <%= link_to "編集する", edit_picture_path(picture.id) %>
  <%= link_to '削除する', picture_path(picture.id), method: :delete, data: { confirm: '本当に消去していいですか？' } %>
<% end %>

<%= link_to "写真をアップロードする", new_picture_path %>

app/views/pictures/new.html.erb
<div class="container">
 <div class="wrapper col-md-4 col-md-offset-4 col-sm-10">

<h2>写真を作成する</h2>

<%= render 'form' %>
 </div>
</div>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Instagram</title>
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="style.css">
</head>

<body>

<header>
       <li><a href="#">Instagram</a></li>
       <li><a href="pictures/new">投稿</a></li>
       <% if user_signed_in? %>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path  %></li>
    <li><%= link_to 'サインアップ', new_user_registration_path %></li>
  <% end %>
  </ul>


</header>

<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<div class="parent">
<img src="<%= asset_path "instagram.png"%>"class="left">
<div class="index">

<div class="picture">
<h1>picture一覧</h1>
<% @pictures.each do |picture| %>
<div class="post">
  <p>タイトル:<%= picture.title %></p>
  <p>本文:<%= picture.content %></p>
  <p><strong>Image:</strong>
   <% picture.image %>
  <%= image_tag picture.image.url %>
  </p>
  <%= link_to "編集する", edit_picture_path(picture.id) %>
  <%= link_to '削除する', picture_path(picture.id), method: :delete, data: { confirm: '本当に消去していいですか？' } %>
<%= picture.user.name %>
</div>
<% end %>
</div>
</div>
</div>

</body>